### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by markrey** [peakhunt/modbus_slave#1]
Looks very nice! I would like to improve it (and remove electron) for some my own testing.
Can you please add a license to it? Apache - MIT would be great.

**Comment by peakhunt** [comment]
sure although I haven't maintained it for a long time and am seeing a need
for a completely new design.

I'll be  sure to change the license to MIT over the weekend.

thanks for your interest.
-H.Kim-

2019년 2월 23일 (토) 오전 8:05, markrey <notifications@github.com>님이 작성:

**Comment by markrey** [comment]
Thanks you very much for a quick feedback!
There are some dependencies and other things i can surely help.

**Comment by markrey** [comment]
MIT license is added. Thanks!
I will keep you posted as i try. Again great work on the project.
